# Cloud Build configuration for ExtraSuite Server
#
# Prerequisites:
#   1. Create a Cloud Build service account with least privileges (see docs/deployment.md)
#   2. Configure a build trigger with these substitution variables:
#      - _REGION: Cloud Run region (e.g., asia-southeast1)
#      - _SERVICE_NAME: Cloud Run service name (e.g., extrasuite)
#      - _RUNTIME_SA: Runtime service account email
#      - _REDIRECT_URI: OAuth callback URL
#      - _ALLOWED_DOMAINS: Comma-separated email domains
#      - _DOMAIN_ABBREVIATIONS: JSON mapping of domains to abbreviations

substitutions:
  _REGION: asia-southeast1
  _SERVICE_NAME: extrasuite
  _RUNTIME_SA: extrasuite-server@${PROJECT_ID}.iam.gserviceaccount.com
  _REDIRECT_URI: https://${_SERVICE_NAME}-565218627358.${_REGION}.run.app/api/auth/callback
  _ALLOWED_DOMAINS: think41.com,recruit41.com,mindlap.dev
  _DOMAIN_ABBREVIATIONS: '{"think41.com":"t41","recruit41.com":"r41","mindlap.dev":"mlap"}'

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'extrasuite-server'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'
      - '.'

  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--service-account=${_RUNTIME_SA}'
      - '--allow-unauthenticated'
      - '--set-secrets=GOOGLE_CLIENT_ID=extrasuite-google-client-id:latest,GOOGLE_CLIENT_SECRET=extrasuite-google-client-secret:latest,SECRET_KEY=extrasuite-secret-key:latest'
      - '--set-env-vars=^@^ENVIRONMENT=production@GOOGLE_CLOUD_PROJECT=$PROJECT_ID@GOOGLE_REDIRECT_URI=${_REDIRECT_URI}@ALLOWED_EMAIL_DOMAINS=${_ALLOWED_DOMAINS}@DOMAIN_ABBREVIATIONS=${_DOMAIN_ABBREVIATIONS}'

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
