steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/extrasuite-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/extrasuite-server:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/extrasuite-server:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/extrasuite-server:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'extrasuite-server'
      - '--image=gcr.io/$PROJECT_ID/extrasuite-server:$COMMIT_SHA'
      - '--region=asia-south1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-secrets=GOOGLE_CLIENT_ID=extrasuite-google-client-id:latest,GOOGLE_CLIENT_SECRET=extrasuite-google-client-secret:latest,SECRET_KEY=extrasuite-secret-key:latest'
      - '--set-env-vars=^::^ENVIRONMENT=production::GOOGLE_CLOUD_PROJECT=$PROJECT_ID::GOOGLE_REDIRECT_URI=https://extrasuite-server-jrq7d3fexa-el.a.run.app/api/auth/callback::ALLOWED_EMAIL_DOMAINS=think41.com,recruit41.com,mindlap.dev'

images:
  - 'gcr.io/$PROJECT_ID/extrasuite-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/extrasuite-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY
